title = "Memorial Implementation Notes"

[scanner]

[scanner.local]
include = [
    "**/src/**/*.rs",
]

[decorators]
external_links = { root = "https://github.com/Kostassoid/memorial/" }

[output]
# root = "docs"
markdown = { path = "IMPLEMENTATION.md", toc = true }
