title = "Posterity Implementation Notes"

[scanner]
# skip-unknown-files = true
# skip-parsing-errors = true

[scanner.local]
# root = "."
include = [
    "**/src/**/*.rs",
]
# exclude = []

[decorators]
external_links = { root = "https://github.com/Kostassoid/posterity/" }

[output]
root = "."
markdown = { path = "IMPLEMENTATION.md", toc = true }
