title = "Posterity Implementation Notes"

[scanner]
# skip-unknown-files = true

[scanner.local]
# root = "."
include = [
    "src/**/*.rs",
]
# exclude = []

[decorators]
external_links = { root = "https://github.com/Kostassoid/posterity/" }

[output]
root = "."
markdown = { path = "IMPLEMENTATION.md", toc = true }
