disable-publish = true
dev-version-ext = "dev"
pre-release-replacements = [
    {file="README.md", search="v[0-9]+\\.[0-9]+\\.[0-9]+", replace="v{{version}}"},
    {file="CHANGELOG.md", search="Unreleased", replace="v{{version}}", min=0},
    {file="CHANGELOG.md", search="ReleaseDate", replace="{{date}}", min=0}
]
